apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
spec:
  params:
    - name: IMAGE
    - name: TAG
    - name: DEPLOYMENT_NAMESPACE
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/dokawa/blue-green-app.git
        - name: subdirectory
          value: ""
        - name: revision
          value: "test-docker"
        - name: deleteExisting
          value: "true"
    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: PATH_CONTEXT
          value: "app"
        - name: ARGS
          value:
            - clean-install
      runAfter:
        - clone-repository
    - name: build-push-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE):$(params.TAG)
        - name: CONTEXT
          value: ""
        - name: FORMAT
          value: "docker"
      runAfter:
        - "install-dependencies"
    - name: deploy-app
      taskRef:
        name: deploy-task
      params:
        - name: DEPLOY_DIR
          value: ./
        - name: VERSION
          value: $(params.TAG)
      runAfter:
        - build-push-image
        # - clone-repository
      workspaces:
        - name: working-dir
          workspace: shared-workspace

      
    - name: blue-green-deploy
      taskRef:
        name: istio-canary
      params:
        - name: VIRTUAL_SERVICE_NAME
          value: blue-green-virtual-service
        - name: APP_NAME
          value: blue-green-app
        - name: NEXT_WEIGHT
          value: 50
        - name: CURRENT_WEIGHT
          value: 50
        - name: GATEWAY_NAME
          value: blue-green-gateway
      runAfter:
        - deploy-app
      workspaces:
        - name: istio-manifest-dir
          workspace: shared-workspace
        
      

